events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream backends {
        server mediabase-backend-1:8080;
        # server mediabase-backend-2:8080;
        # server mediabase-backend-3:8080;
        # Docker will resolve multiple backend containers automatically
    }

    server {
        listen 80;
        # server_name _;

        location /api/ {
            proxy_pass http://backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}