events {}

http {
    upstream backend_cluster {
        server backend:8080;
        # Docker will resolve multiple backend containers automatically
    }

    server {
        listen 80;

        location /search/ {
            proxy_pass http://backend_cluster/;
        }

        location /user/ {
            proxy_pass http://backend_cluster/;
        }
        
        location /media/ {
            proxy_pass http://backend_cluster/;
        }

        location /person/ {
            proxy_pass http://backend_cluster/;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }
    }
}